project:
  type: website
  output-dir: docs
  preview:
    port: 4200

website:
  page-navigation: true
  title: "yongrae's website"
  site-url: "https://yongraegod.com"
  navbar:
    right:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About Me
      - href: blog.qmd
        text: Blog

format:
  html:
    theme: cosmo
    # css: styles.css
    toc: True



